### ISSUE TITLE
매장정보, 마커 검색 기능 구현

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#10]
**Description**
-
매장 정보 UI, 그룹박스 클릭하면 border 색 주기

**Todo**
-
- [ ] 매장정보 UI 구현
- [ ] 마커 클릭하면 매장정보 업데이트
- [ ] 그룹박스 클릭하면 마커 필터링하기
- [ ] 검색바로 검색하면 마커 필터링하기

**ETC**
-
매장정보 표에 에러 발생시간은 없으니까 비워두기
