### ISSUE TITLE
feat: 슬라이스 생성

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#16]
**Description**
-
고객상세페이지 슬라이스 생성

**Todo**
-
- [ ] 검색바를 통해서 매장 목록 검색하기
- [ ] 클릭된 마커, 선택된 매장 슬라이스 생성하기
- [ ] 상세페이지 레이아웃 잡기

**ETC**
-
없음
