### ISSUE TITLE
feat: 고객상세페이지 UI 구현

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#20]
**Description**
-
고객상세페이지 UI구현
**Todo**
-
- [x] 검색 결과 여러개일 시 매장목록 보여주기
- [x] 매장목록 클릭시 상세 정보 보여주기
- [x] 도면, 이력관리, 디바이스 정보 레이아웃 작성

**ETC**
-
없음
