### ISSUE TITLE
feat: 고객상세페이지 세부사항 추가

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#26]
**Description**
-
고객상세페이지에 빠진 기타사항 기능명세서 보고 추가

**Todo**
-
- [ ] 매장정보관리탭 생성
- [ ] 매장정보관리탭 입력 기능
- [ ] 도면 기능 설치버튼 누르면 아이콘보드 출력
- [ ] 에러 이력 클릭하면 UI갱신

**ETC**
-
기타사항
