### ISSUE TITLE
feat: 나의업무 진행상태 상태값으로 관리

### ISSUE THREAD

**Issue by sjgske** [seedn-fe/cs-tool-fe-admin#41]
**Description**
-
나의업무 진행상태 상태값으로 관리 (api 연동 위해)

**Todo**
-
- [x] listContent 목데이터 구조 수정
- [x] tabMenu -> 진행 상태에 따라 필터링하는 방식으로 로직 수정
- [x] 출동관리 동행인원 선택값 가져오기

**ETC**
-
기타사항
