### ISSUE TITLE
chore: 다운로드 템플릿 기능 삭제, 눈금 지우기 기능

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#44]
**Description**
-
다운로드 템플릿 기능 삭제, 눈금 지우기 기능

**Todo**

- [x] 다운로드 템플릿 삭제하고 svg만 png파일로 저장
- [x] 아이템 삭제 기능
- [x] 아이콘 드래그 기능

**ETC**
-
기타사항
