### ISSUE TITLE
대시보드 페이지 그룹박스 UI 구현

### ISSUE THREAD

**Issue by hank1245** [seedn-fe/cs-tool-fe-admin#5]
**Description**
-
대시보드 페이지 그룹박스 UI를 구현한다

**Todo**
-
- [x] 그룹별로 박스를 생성하고 그룹이름, 해당하는 기기갯수를 표시한다.
- [x] 그룹 박스를 클릭하면 기기 위치 지도에 해당하는 단계의 마커만 표시된다.
- [x] 여러개의 그룹 박스를 클릭한 경우 모든 클릭된 단계의 마커를 표시한다.
- [x] 그룹 박스가 클릭된 경우 클릭되었다는 것을 알 수 있도록 border의 색깔을 변경한다.

**ETC**
-
등록된 기기들을 그룹별로 조회한다.
1) 그룹 이름은 1단계, 2단계, 3단계로 한다
1-1) 1단계는 Server-Hub간 연결 끊김 상태(hasPower = 0)이다
1-2)2단계는 Hub-slave 간 연결 끊김 상태(허브 hasPower = 1, Slave hasPower = 0)이다.
1-3)3단계는 Slave 배터리가 2700 이하인 상태이다.
