### ISSUE TITLE
고객상세페이지 UI 누락된 사항 수정

### ISSUE THREAD

**Issue by sjgske** [seedn-fe/cs-tool-fe-admin#55]
**Description**
-
고객상세페이지 UI 누락된 사항 수정

**Todo**
-
- [x] 이력추가 - 상담경로 select 수정
- [x] 매장정보 - 설치자 추가하기
- [x] 계약관리 - 디바이스 개수 → 허브,센서,컨트롤러 따로따로 → input 3개로 수정하기

**ETC**
-
기타사항
